services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000" 
    container_name: wbd-backend
    env_file:
      - ./backend/.env.production
    depends_on:
      - db
      - redis
    networks:
      - wbd-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173" 
    container_name: wbd-frontend
    depends_on:
      - backend
    networks:
      - wbd-network

  db:
    image: postgres:latest
    container_name: postgres-db
    restart: always
    ports:
      - "5433:5432" 
    env_file:
      - ./backend/.env.production
    volumes:
      - postgres_data:/var/lib/postgresql/data 
      - ./backend/db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - wbd-network

  redis:
    image: redis:latest
    container_name: redis-cache
    restart: always
    ports:
      - "6379:6379" 
    volumes:
      - redis_data:/data 
    networks:
      - wbd-network

networks:
  wbd-network:

volumes:
  postgres_data:
  redis_data:
